name: Update package.json version

on:
  push:
    branches:
      - test-version-update

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Update package.json version
        uses: reedyuk/npm-version@1.1.1
        with:
          version: patch

      - name: Commit Updated package.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated package.json
