# This workflow will update the package.json version number when a release is drafted

name: Update Version Number

on:
  release:
    types: [draft]

jobs:
  npm-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm version patch